networks:
  portfolio-frontend-network:
    name: portfolio-frontend-network
  portfolio-backend-network:
    name: portfolio-backend-network

volumes:
  database:

services:
  proxy:
    container_name: portfolio_proxy
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/portfolio.conf:ro
    image: nginx:1.21
    depends_on:
      - frontend
      - backend
    networks:
      - portfolio-frontend-network
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80

  frontend:
    container_name: portfolio_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      # - /app/node_modules
    build:
      context: .
      dockerfile: infra/docker/frontend.Dockerfile
    networks:
      - portfolio-frontend-network
    expose:
      - 3000

  backend:
    container_name: portfolio_backend
    working_dir: /app
    volumes:
      - ./backend:/app
      # - /app/node_modules
    build:
      context: .
      dockerfile: infra/docker/backend.Dockerfile
    depends_on:
      - db
    env_file: backend.env
    networks:
      - portfolio-frontend-network
      - portfolio-backend-network
    expose:
      - 3000

  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_PASSWORD=S3TtM9kbobM7iLnP
    networks:
      - portfolio-backend-network
    ports:
      - 5432:5432

  flyway:
    image: flyway/flyway
    volumes:
      - ./db/migrations:/flyway/sql
    command: -url=jdbc:postgresql://db:5432/ -schemas=perth-toilets -user=postgres -password=S3TtM9kbobM7iLnP -connectRetries=60 migrate
    networks:
      - portfolio-backend-network
    depends_on:
      - db